branch-defaults:
  lesson-2-exercise-1:
    environment: Projectapp-env
environment-defaults:
  Projectapp-env:
    branch: null
    repository: null
global:
  application_name: project-app
  default_ec2_keyname: null
  default_platform: Node.js 16 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
